### Register user
POST  https://mern-calendar-angeleraser.herokuapp.com/api/auth/register
Content-Type: application/json

{
    "name": "Pedrosete",
    "email": "pedrosete@gmail.com",
    "password": "123456"
}

### Login user
POST https://mern-calendar-angeleraser.herokuapp.com/api/auth
Content-Type: application/json

{
    "email": "pedrosete@gmail.com",
    "password": "123456"
}
### Renew Token
GET https://mern-calendar-angeleraser.herokuapp.com/api/auth/renew-token
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZjlhZWQwMzI4MjMwOTAzMWNiMWZiNTUiLCJuYW1lIjoiUGVkcm9zZXRlIiwiaWF0IjoxNjA0MDAwMDEwLCJleHAiOjE2MDQwMDcyMTB9.KHXsyPFjNU_vnbYsughdZZxQB6vBfWxBi-fy_tGkiCo
Content-Type: application/json

