### Register user
POST  https://mern-calendar-angeleraser.herokuapp.com/api/auth
Content-Type: application/json

{
    "name": "Pedrosete",
    "email": "pedrosete@gmail.com",
    "password": "123456"
}

### Login user
POST https://mern-calendar-angeleraser.herokuapp.com/api/auth
Content-Type: application/json

{
    "email": "pedrosete@gmail.com",
    "password": "123456"
}
### Renew Token
GET https://mern-calendar-angeleraser.herokuapp.com/api/auth/renew-token
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1Zjk5ZDM3MGQ1MmU2YzFiYTBhYjVlYjkiLCJuYW1lIjoiQW5nZWwiLCJpYXQiOjE2MDM5MTY2NTcsImV4cCI6MTYwMzkyMzg1N30.HuzLxXNtBMpmbU3kotORZm3pdOhY8jtrXIX-pb9uDoo
Content-Type: application/json

