### Obtener eventos
GET https://mern-calendar-angeleraser.herokuapp.com/api/events HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZjlhZWQwMzI4MjMwOTAzMWNiMWZiNTUiLCJuYW1lIjoiUGVkcm9zZXRlIiwiaWF0IjoxNjA0MDAwMTAxLCJleHAiOjE2MDQwMDczMDF9.JQRZthLBUdkWCtFhvitgZd9jGspZtuTfSegdpGZbOO8
Content-Type: application/json

### Crear un nuevo evento
POST  https://mern-calendar-angeleraser.herokuapp.com/api/events HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZjlhZWQwMzI4MjMwOTAzMWNiMWZiNTUiLCJuYW1lIjoiUGVkcm9zZXRlIiwiaWF0IjoxNjA0MDAwMTAxLCJleHAiOjE2MDQwMDczMDF9.JQRZthLBUdkWCtFhvitgZd9jGspZtuTfSegdpGZbOO8
Content-Type: application/json

{
    "title":"Learn Pedrosete olololol",
    "start":4000000000,
    "end":5000000000
}

### Acualizar evento
PUT https://mern-calendar-angeleraser.herokuapp.com/api/events/5f9acc5f9112e005a84cff94 HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZjlhZWQwMzI4MjMwOTAzMWNiMWZiNTUiLCJuYW1lIjoiUGVkcm9zZXRlIiwiaWF0IjoxNjAzOTg4NzM5LCJleHAiOjE2MDM5OTU5Mzl9.PHP87C1t02ZKxZC33iNrp5Pwp_aUsis3ER9DF2Vec_I
Content-Type: application/json

{
    "title":"Learn mySQLPedrosete",
    "start":8000000000,
    "end":100000000000
}

### Borrar evento
DELETE  https://mern-calendar-angeleraser.herokuapp.com/api/events/5f9aed23282309031cb1fb56 HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZjlhZWQwMzI4MjMwOTAzMWNiMWZiNTUiLCJuYW1lIjoiUGVkcm9zZXRlIiwiaWF0IjoxNjA0MDAwMTAxLCJleHAiOjE2MDQwMDczMDF9.JQRZthLBUdkWCtFhvitgZd9jGspZtuTfSegdpGZbOO8
Content-Type: application/json